"""add source to contact analysis

Revision ID: 0bcb9f5bfde8
Revises: 6971b3501afd
Create Date: 2026-07-28 13:46:58.817295

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0bcb9f5bfde8"
down_revision: Union[str, Sequence[str], None] = "6971b3501afd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contact_analyses", sa.Column("source", sa.String(length=20), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contact_analyses", "source")
    # ### end Alembic commands ###
