"""add contact analysis

Revision ID: 6971b3501afd
Revises: 57038753be5e
Create Date: 2026-07-28 13:26:06.463415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6971b3501afd'
down_revision: Union[str, Sequence[str], None] = '57038753be5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_request_id', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_request_id'], ['contact_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_analyses_id'), 'contact_analyses', ['id'], unique=False)
    op.drop_column('contact_requests', 'sentiment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_requests', sa.Column('sentiment', sa.VARCHAR(length=50), nullable=True))
    op.drop_index(op.f('ix_contact_analyses_id'), table_name='contact_analyses')
    op.drop_table('contact_analyses')
    # ### end Alembic commands ###
